name: Build, Lint, and Test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "packages/**"
jobs:
  build-lint-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get Yarn cache directory
        run: echo "::set-output name=YARN_CACHE_DIR::$(yarn cache dir)"
        id: yarn-cache-dir
      - name: Get Yarn version
        run: echo "::set-output name=YARN_VERSION::$(yarn --version)"
        id: yarn-version
      - name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.YARN_CACHE_DIR }}
          key: yarn-cache-${{ runner.os }}-${{ steps.yarn-version.outputs.YARN_VERSION }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install --no-immutable
      - run: yarn setup
      - run: yarn npm audit
      - run: yarn clean
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - name: SonarCloud Scan Starknet-Snap
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        with:
          projectBaseDir: packages/starknet-snap/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_STARKNET_SNAP }}
      - name: SonarCloud Scan Wallet-UI
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        with:
          projectBaseDir: packages/wallet-ui/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_WALLET_UI }}