name: Publish get-starknet Dev to NPM
on:
  push:
    branches:
      - main
      - 'feat/add-get-starknet-package'
      - 'releases/**'
    paths:
      - "packages/get-starknet"
permissions:
  contents: write
jobs:
  publish-get-starknet-to-npm:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - run: |
          yarn install --no-immutable
          yarn workspace @consensys/get-starknet setup
          VERSION=$(node -p "require('./packages/get-starknet/package.json').version")
          HASH=$(git rev-parse --short HEAD)
          DATE=$(date +%Y%m%d%H%M%S)
          npm --prefix ./packages/get-starknet version --new-version ${VERSION}-dev-${HASH}-${DATE} --no-git-tag-version
          yarn workspace @consensys/get-starknet build

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish ./packages/get-starknet --tag dev --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
