name: Publish Dev to NPM
on:
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - "packages/**"
permissions:
  contents: write
# defaults:
#   run:
#     working-directory: ./packages/starknet-snap
jobs:
  publish-dev-to-npm:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - run: |
          yarn install --no-immutable
          yarn workspace @consensys/starknet-snap setup
          VERSION=$(node -p "require('./packages/starknet-snap/package.json').version")
          HASH=$(git rev-parse --short HEAD)
          DATE=$(date +%Y%m%d)
          npm --prefix ./packages/starknet-snap version --new-version ${VERSION}-dev-${HASH}-${DATE} --no-git-tag-version
          SNAP_ENV=dev yarn workspace @consensys/starknet-snap build

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish ./packages/starknet-snap --tag dev --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
