name: Deploy get-starknet package to s3
on:
  push:
    branches:
      - main
    paths:
      - "packages/get-starknet/**"
      
permissions:
  contents: write
jobs:
  publish-get-starknet-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install --no-immutable
          yarn workspace @consensys/get-starknet setup
          yarn workspace @consensys/get-starknet build:fed

      - name: Deploy to Dev
        run: | 
          aws s3 sync ./packages/get-starknet/dist/webpack s3://dev.snaps.consensys.io/get-starknet
          aws s3 sync ./packages/get-starknet/dist/jsonp s3://dev.snaps.consensys.io/get-starknet
